Configure script. Installation fixes. Daemon execution.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,8 +1,15 @@
 #!/bin/sh
 
-if [ -z "${PREFIX}" ] ; then
-	PREFIX=/usr/local
-fi
+# Proprietary configure script of TURN Server project
+
+cleanup() {
+	rm -rf ${TMPCPROGC}
+	rm -rf ${TMPCPROGB}
+	rm -rf ${TH_TMPCPROGC}
+	rm -rf ${TH_TMPCPROGB}
+	rm -rf ${D_TMPCPROGC}
+	rm -rf ${D_TMPCPROGB}
+}
 
 testlibraw() {
     ${CC} ${TMPCPROGC} -o ${TMPCPROGB} ${OSCFLAGS} ${OSLIBS} -${1} 2>/dev/null
@@ -22,37 +29,78 @@ testlib() {
 
 pthread_testlib() {
 
-    testlibraw pthread
-    ER=$?
-    if [ ${ER} -eq 0 ] ; then
-    	testlib pthread
+	if [ -z "${PTHREAD_LIBS}" ] ; then
+    	testlibraw pthread
+    	ER=$?
+    	if [ ${ER} -eq 0 ] ; then
+    		testlib pthread
+    	fi
+    else
+    	OSLIBS="${OSLIBS} ${PTHREAD_LIBS}"
     fi
 
     ${CC} ${TH_TMPCPROGC} -o ${TH_TMPCPROGB} ${OSCFLAGS} ${OSLIBS} 2>/dev/null
     ER=$?
     if ! [ ${ER} -eq 0 ] ; then
-	${CC} ${TH_TMPCPROGC} -o ${TH_TMPCPROGB} ${OSCFLAGS} ${OSLIBS} -D_GNU_SOURCE 2>/dev/null
-	ER=$?
-	if ! [ ${ER} -eq 0 ] ; then
-	    echo "Do not use pthreads"
-	    return 0
-	else 
-	    echo "Older GNU pthread library found"
-	    OSCFLAGS="${OSCFLAGS} -D_GNU_SOURCE"
-	    return 1
-	fi
-    else
-	return 1
+		${CC} ${TH_TMPCPROGC} -o ${TH_TMPCPROGB} ${OSCFLAGS} ${OSLIBS} -D_GNU_SOURCE 2>/dev/null
+		ER=$?
+		if ! [ ${ER} -eq 0 ] ; then
+	    	echo "Do not use pthreads"
+	    	return 0
+		else 
+	    	echo "Older GNU pthread library found"
+	    	OSCFLAGS="${OSCFLAGS} -D_GNU_SOURCE"
+	    	return 1
+		fi
+    	else
+		return 1
     fi
 }
+
+testdaemon() {
+
+	${CC} ${D_TMPCPROGC} -o ${D_TMPCPROGB} ${OSCFLAGS} ${OSLIBS} 2>/dev/null
+    ER=$?
+    if [ ${ER} -eq 0 ] ; then
+		OSCFLAGS="${OSCFLAGS} -DHAS_DAEMON"
+	fi
+}
+
+#########################
+# Start
+#########################
+
+cleanup
 
 #########################
 # To be set:
 #########################
-OSCFLAGS=
-OSLIBS="-L${PREFIX}/lib/event2/ -L${PREFIX}/lib/ -Llib"
+
+if [ -z "${PREFIX}" ] ; then
+	PREFIX=/usr/local
+fi
+
+if [ -z "${MANPREFIX}" ] ; then
+	MANPREFIX=${PREFIX}
+fi
+
+if [ -z "${ARCHIVERCMD}" ] ; then
+	ARCHIVERCMD="ar -r"
+fi
+
+OSCFLAGS="${CFLAGS}"
+OSLIBS="${LDFLAGS} -L${PREFIX}/lib/event2/ -L${PREFIX}/lib/ -Llib -L/usr/local/lib/event2/ -L/usr/local/lib/"
 TURN_NO_THREADS=
 TURN_NO_TLS=
+
+MKDIR="mkdir -p"
+INSTALL_PROGRAM="cp -f"
+INSTALL_MAN="cp -f"
+INSTALL_SCRIPT="cp -f"
+INSTALL_LIB="cp -f"
+INSTALL_DATA="cp -f"
+INSTALL_DIR="cp -rf"
+RMCMD="rm -rf"
 
 #############################
 # Adjustments for Solaris
@@ -105,6 +153,18 @@ int main() {
 }
 !
 
+D_TMPCPROG=__test__ccomp__daemon__$$
+D_TMPCPROGC=${TMPDIR}/${D_TMPCPROG}.c
+D_TMPCPROGB=${TMPDIR}/${D_TMPCPROG}
+
+cat > ${D_TMPCPROGC} <<!
+#include <stdlib.h>
+#include <unistd.h>
+int main() {
+    return (int)daemon(0,0);
+}
+!
+
 ##########################
 # What is our compiler ?
 ##########################
@@ -134,6 +194,7 @@ ${CC} ${TMPCPROGC} ${OSCFLAGS} -o ${TMPCPROGB}
 ER=$?
 if ! [ ${ER} -eq 0 ] ; then
     echo "ERROR: cannot use compiler ${CC} properly"
+    cleanup
     exit
 fi
 
@@ -174,6 +235,12 @@ if [ ${ER} -eq 0 ] ; then
 fi
 
 ###########################
+# Can we use daemon ?
+###########################
+
+testdaemon
+
+###########################
 # Test OpenSSL installation
 ###########################
 
@@ -182,8 +249,9 @@ ER=$?
 if ! [ ${ER} -eq 0 ] ; then
     echo "SSL lib found."
 else
-    echo "ERROR: OpenSSL development libraries are not installed properly in ${PREFIX}."
+    echo "ERROR: OpenSSL development libraries are not installed properly in required location."
     echo "Abort."
+    cleanup
     exit
 fi
 
@@ -192,8 +260,9 @@ ER=$?
 if ! [ ${ER} -eq 0 ] ; then
     echo "Crypto SSL lib found."
 else
-    echo "ERROR: OpenSSL Crypto development libraries are not installed properly in ${PREFIX}."
+    echo "ERROR: OpenSSL Crypto development libraries are not installed properly in required location."
     echo "Abort."
+    cleanup
     exit
 fi
 
@@ -206,9 +275,10 @@ ER=$?
 if ! [ ${ER} -eq 0 ] ; then
     echo "Libevent2 found."
 else
-    echo "ERROR: Libevent2 development libraries are not installed properly in ${PREFIX}."
+    echo "ERROR: Libevent2 development libraries are not installed properly in required location."
     echo "See the INSTALL file."
     echo "Abort."
+    cleanup
     exit
 fi
 
@@ -238,13 +308,40 @@ fi
 # So, what we have now:
 ###############################
 
-OSCFLAGS="${OSCFLAGS} ${TURN_NO_THREADS} ${TURN_NO_TLS} -D__USE_OPENSSL__"
+OSCFLAGS="${OSCFLAGS} ${TURN_NO_THREADS} ${TURN_NO_TLS} -D__USE_OPENSSL__ -DINSTALL_PREFIX=${PREFIX}"
 
 echo make PREFIX=${PREFIX} OSLIBS="${OSLIBS}" OSCFLAGS="${OSCFLAGS}" $@
 
 ###############################
-# Run make:
+# Make make:
 ###############################
 
-make PREFIX=${PREFIX} OSLIBS="${OSLIBS}" OSCFLAGS="${OSCFLAGS}" -f Makefile.all $@
+echo "#################################" > Makefile
+echo "# Generated by configure script #" >> Makefile
+echo "#################################" >> Makefile
+echo "PREFIX = ${PREFIX}" >> Makefile
+echo "MANPREFIX = ${MANPREFIX}" >> Makefile
+echo "LDFLAGS += ${OSLIBS}" >> Makefile
+echo "CFLAGS += ${OSCFLAGS}" >> Makefile
+echo "ARCHIVERCMD = ${ARCHIVERCMD}" >> Makefile
+echo "MKDIR = ${MKDIR}" >> Makefile
+echo "INSTALL_PROGRAM = ${INSTALL_PROGRAM}" >> Makefile
+echo "INSTALL_MAN = ${INSTALL_MAN}" >> Makefile
+echo "INSTALL_SCRIPT = ${INSTALL_SCRIPT}" >> Makefile
+echo "INSTALL_LIB = ${INSTALL_LIB}" >> Makefile
+echo "INSTALL_DATA = ${INSTALL_DATA}" >> Makefile
+echo "INSTALL_DIR = ${INSTALL_DIR}" >> Makefile
+echo "RMCMD = ${RMCMD}" >> Makefile
+echo "################################" >> Makefile
+echo "" >> Makefile
+cat Makefile.in >> Makefile
+
+#make PREFIX=${PREFIX} OSLIBS="${OSLIBS}" OSCFLAGS="${OSCFLAGS}" -f Makefile.all $@
+
+###############################
+# End:
+###############################
+
+cleanup
+
 
